eksctl create cluster \
    --name kubeflow-sm \
    --version 1.17 \
    --region eu-west-1 \
    --nodegroup-name cpu-nodes \
    --node-type c5.xlarge \
    --nodes 2 \
    --node-volume-size 50 \
    --node-zones eu-west-1a \
    --timeout=40m \
    --auto-kubeconfig
